version: '3'
services:
  bot:
    container_name: vp_bot
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    tty: true
    env_file:
      - ./.env
    environment:
      - token=${prod_token}
      - env_type=production
      - TZ=Europe/Paris
    networks:
      - global

networks:
  global: