services:
  bot:
    container_name: vp_bot_dev
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.dev
    tty: true
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env
    environment:
      - TOKEN=${DEV_TOKEN}
      - GNEWS_TOKEN=${GNEWS_TOKEN}
      - WEATHER_TOKEN=${WEATHER_TOKEN}
      - GUILD_ID=${GUILD_ID}
      - MSG_TODAY_CHANNEL=${MSG_TODAY_CHANNEL}
      - BIRTHDAY_ROLE=${BIRTHDAY_ROLE}
      - ENV_TYPE=development
      - TZ=Europe/Paris

volumes:
  data: