FROM node:22-alpine AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

ARG BUILDARCH

WORKDIR /app

ENV TZ Europe/Paris

RUN apk update && \
    apk upgrade && \
    apk add --no-cache \
        # node-gyp
        libstdc++ build-base python3 make g++ gcc pkgconfig \
        # Canvas (dev version)
        pixman-dev cairo-dev pango-dev libjpeg-turbo-dev giflib-dev librsvg-dev \
        # Canvas (runtime version)
        pixman cairo pango libjpeg-turbo giflib librsvg gcompat

FROM node-${BUILDARCH} AS final

COPY --chown=node:node package.json pnpm-lock.yaml ./
COPY --chown=node:node tsconfig.json ./

RUN pnpm install

COPY --chown=node:node ./src ./src
COPY --chown=node:node ./src/assets ./dist/assets
COPY --chown=node:node .env .

CMD npx tsc-watch --onSuccess "node dist/index.js"