FROM node:22-alpine AS base

ARG BUILDARCH

WORKDIR /app

ENV TZ Europe/Paris

FROM base AS node-amd64

RUN apk update && \
    apk upgrade && \
    apk add --no-cache wget ca-certificates build-base python3 fontconfig ttf-bitstream-vera dumb-init

FROM base AS node-arm64

RUN apk update && \
    apk upgrade && \
    apk add --no-cache \
        # node-gyp
        libstdc++ build-base python3 make g++ gcc pkgconfig \
        # Canvas (dev version)
        pixman-dev cairo-dev pango-dev libjpeg-turbo-dev giflib-dev librsvg-dev \
        # Canvas (runtime version)
        pixman cairo pango libjpeg-turbo giflib librsvg gcompat

FROM node-${BUILDARCH} AS final

COPY --chown=node:node package.json yarn.lock ./
COPY --chown=node:node tsconfig.json ./

RUN yarn install

COPY --chown=node:node ./src ./src
COPY --chown=node:node ./src/assets ./dist/assets
COPY --chown=node:node .env .

CMD npx tsc-watch --onSuccess "node dist/index.js"